import { Plan } from '../types/pricing';

export const PLANS: Plan[] = [
  {
    id: 'free',
    name: 'Free',
    monthlyPrice: 0,
    yearlyPrice: 0,
    description: 'Best for small or one-time events',
    cta: 'Get Started Free',
    ctaVariant: 'outline',
    popular: false,
    features: [
      '1 active badge campaign',
      'Basic badge templates',
      'Shareable link',
      'Limited customization',
      'Watermark included',
    ],
  },
  {
    id: 'pro',
    name: 'Pro',
    monthlyPrice: 30,
    yearlyPrice: 24,
    description: 'For growing teams and organizers',
    cta: 'Upgrade to Pro',
    ctaVariant: 'primary',
    popular: true,
    features: [
      'Up to 5 active campaigns',
      'Premium templates',
      'Shareable link',
      'Advanced customization',
      'Basic analytics',
      'Custom link / URL',
      'Watermark removed',
    ],
  },
  {
    id: 'team',
    name: 'Team',
    monthlyPrice: 50,
    yearlyPrice: 40,
    description: 'For large events and organizations',
    cta: 'Upgrade to Team',
    ctaVariant: 'outline',
    popular: false,
    features: [
      'Unlimited active campaigns',
      'All templates + custom upload',
      'Shareable link',
      'Full branding & customization',
      'Advance dashboard & analytics',
      'Custom link / URL',
      'API access & integrations',
      'Watermark removed',
    ],
  },
];